/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAgentFeedRouteImport } from './routes/api/agent/feed'
import { Route as ApiAgentInitRouteImport } from './routes/api/agent/init'
import { Route as ApiInterviewEndRouteImport } from './routes/api/interview/end'
import { Route as ApiInterviewMessageRouteImport } from './routes/api/interview/message'
import { Route as ApiInterviewStartRouteImport } from './routes/api/interview/start'
import { Route as ApiInterviewFeedbackSessionIdRouteImport } from './routes/api/interview/feedback/$sessionId'
import { Route as ApiInterviewSessionSessionIdRouteImport } from './routes/api/interview/session/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentFeedRoute = ApiAgentFeedRouteImport.update({
  id: '/api/agent/feed',
  path: '/api/agent/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentInitRoute = ApiAgentInitRouteImport.update({
  id: '/api/agent/init',
  path: '/api/agent/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewEndRoute = ApiInterviewEndRouteImport.update({
  id: '/api/interview/end',
  path: '/api/interview/end',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewMessageRoute = ApiInterviewMessageRouteImport.update({
  id: '/api/interview/message',
  path: '/api/interview/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewStartRoute = ApiInterviewStartRouteImport.update({
  id: '/api/interview/start',
  path: '/api/interview/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewFeedbackSessionIdRoute =
  ApiInterviewFeedbackSessionIdRouteImport.update({
    id: '/api/interview/feedback/$sessionId',
    path: '/api/interview/feedback/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInterviewSessionSessionIdRoute =
  ApiInterviewSessionSessionIdRouteImport.update({
    id: '/api/interview/session/$sessionId',
    path: '/api/interview/session/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/agent/feed': typeof ApiAgentFeedRoute
  '/api/agent/init': typeof ApiAgentInitRoute
  '/api/interview/end': typeof ApiInterviewEndRoute
  '/api/interview/message': typeof ApiInterviewMessageRoute
  '/api/interview/start': typeof ApiInterviewStartRoute
  '/api/interview/feedback/$sessionId': typeof ApiInterviewFeedbackSessionIdRoute
  '/api/interview/session/$sessionId': typeof ApiInterviewSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/agent/feed': typeof ApiAgentFeedRoute
  '/api/agent/init': typeof ApiAgentInitRoute
  '/api/interview/end': typeof ApiInterviewEndRoute
  '/api/interview/message': typeof ApiInterviewMessageRoute
  '/api/interview/start': typeof ApiInterviewStartRoute
  '/api/interview/feedback/$sessionId': typeof ApiInterviewFeedbackSessionIdRoute
  '/api/interview/session/$sessionId': typeof ApiInterviewSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/setup': typeof SetupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/agent/feed': typeof ApiAgentFeedRoute
  '/api/agent/init': typeof ApiAgentInitRoute
  '/api/interview/end': typeof ApiInterviewEndRoute
  '/api/interview/message': typeof ApiInterviewMessageRoute
  '/api/interview/start': typeof ApiInterviewStartRoute
  '/api/interview/feedback/$sessionId': typeof ApiInterviewFeedbackSessionIdRoute
  '/api/interview/session/$sessionId': typeof ApiInterviewSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/setup'
    | '/api/health'
    | '/api/agent/feed'
    | '/api/agent/init'
    | '/api/interview/end'
    | '/api/interview/message'
    | '/api/interview/start'
    | '/api/interview/feedback/$sessionId'
    | '/api/interview/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/setup'
    | '/api/health'
    | '/api/agent/feed'
    | '/api/agent/init'
    | '/api/interview/end'
    | '/api/interview/message'
    | '/api/interview/start'
    | '/api/interview/feedback/$sessionId'
    | '/api/interview/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/setup'
    | '/api/health'
    | '/api/agent/feed'
    | '/api/agent/init'
    | '/api/interview/end'
    | '/api/interview/message'
    | '/api/interview/start'
    | '/api/interview/feedback/$sessionId'
    | '/api/interview/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  SetupRoute: typeof SetupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAgentFeedRoute: typeof ApiAgentFeedRoute
  ApiAgentInitRoute: typeof ApiAgentInitRoute
  ApiInterviewEndRoute: typeof ApiInterviewEndRoute
  ApiInterviewMessageRoute: typeof ApiInterviewMessageRoute
  ApiInterviewStartRoute: typeof ApiInterviewStartRoute
  ApiInterviewFeedbackSessionIdRoute: typeof ApiInterviewFeedbackSessionIdRoute
  ApiInterviewSessionSessionIdRoute: typeof ApiInterviewSessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/feed': {
      id: '/api/agent/feed'
      path: '/api/agent/feed'
      fullPath: '/api/agent/feed'
      preLoaderRoute: typeof ApiAgentFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/init': {
      id: '/api/agent/init'
      path: '/api/agent/init'
      fullPath: '/api/agent/init'
      preLoaderRoute: typeof ApiAgentInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview/end': {
      id: '/api/interview/end'
      path: '/api/interview/end'
      fullPath: '/api/interview/end'
      preLoaderRoute: typeof ApiInterviewEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview/message': {
      id: '/api/interview/message'
      path: '/api/interview/message'
      fullPath: '/api/interview/message'
      preLoaderRoute: typeof ApiInterviewMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview/start': {
      id: '/api/interview/start'
      path: '/api/interview/start'
      fullPath: '/api/interview/start'
      preLoaderRoute: typeof ApiInterviewStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview/feedback/$sessionId': {
      id: '/api/interview/feedback/$sessionId'
      path: '/api/interview/feedback/$sessionId'
      fullPath: '/api/interview/feedback/$sessionId'
      preLoaderRoute: typeof ApiInterviewFeedbackSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview/session/$sessionId': {
      id: '/api/interview/session/$sessionId'
      path: '/api/interview/session/$sessionId'
      fullPath: '/api/interview/session/$sessionId'
      preLoaderRoute: typeof ApiInterviewSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  SetupRoute: SetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAgentFeedRoute: ApiAgentFeedRoute,
  ApiAgentInitRoute: ApiAgentInitRoute,
  ApiInterviewEndRoute: ApiInterviewEndRoute,
  ApiInterviewMessageRoute: ApiInterviewMessageRoute,
  ApiInterviewStartRoute: ApiInterviewStartRoute,
  ApiInterviewFeedbackSessionIdRoute: ApiInterviewFeedbackSessionIdRoute,
  ApiInterviewSessionSessionIdRoute: ApiInterviewSessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
